### ISSUE TITLE
it's not work!

### ISSUE THREAD

**Issue by MadShura** [bestiejs/benchmark.js#227]
code:
var arr = [2,3];
// add tests
suite.add('arr.length--', function () {  
    arr.length = arr.length -1
})
    .add('arr.pop()', function () {      
        arr.pop()
    })

output:
arr.length--:
arr.pop() x 507,851,390 ops/sec ±0.35% (72 runs sampled)

why the arr.length-- is not work .
thanks

**Comment by beaunus** [comment]
@MadShura I think that the problem may be that the function in the `arr.length--` test throws an error on the third iteration. If you run this code, you will see what error is thrown.

```
var arr = [2,3];

arr.length = arr.length - 1;
arr.length = arr.length - 1;
arr.length = arr.length - 1;
// Uncaught RangeError: Invalid array length
```

Thus, it seems that if a test throws an error, its results are ignored.

Here is an example of what happens when a test _explicitly_ throws an error.

```js
  var arr = [2, 3];
  suite
    .add('arr.length--', function() {
      arr.length = arr.length - 1;
    })
    .add('throw new Error()', function() {
      // This behaves the same as the `arr.length--` test above.
      throw new Error();
    })
    .add('arr.pop()', function() {
      arr.pop();
    })
```

There may be a better way of dealing with errors within tests. What do you think?

**Comment by MadShura** [comment]
i got it ,thank you ~
