### ISSUE TITLE
asynchronous benchmark setup.

### ISSUE THREAD

**Issue by startling** [bestiejs/benchmark.js#53]
I have some things I need to do asynchronously in a setup function. As far as I can tell, there's no way to do this -- if there is, I apologize!

Here's an example (for node) of the kind of thing I want to be able to do:

``` js
var fs = require("fs");
var Benchmark = require("benchmark");

new Benchmark.Suite().
  add("Test with asynchronous setup", {
    'defer': true,
    'setup': function (deferred) {
      var _this = this;
      fs.readFile("data.txt", function (_, data) {
        _this.data = data;
        deferred.resolve();
      });
    },
    'fn': function (deferred) {
      console.log(this.data);
      deferred.resolve();
    }
  }).
  run();
```

**Comment by shamasis** [comment]
@jdalton since sync things are not that good and I have some async crypto work as part pf setup. we should consider deferring setup.

You could use `function.length` to check if setup has a callback argument defined and then wait for it to be called. If you are interested, we can discuss sending a PR.
